language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - gem install reek --no-document

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
